version: '3.1'

services:

  db:
    image: postgres
    restart: always
    volumes:
      C:\Users\Pepper\IdeaProjects\Docker\docker-compose.yml:/var/lib/postgresql/data:
    environment:
      -e POSTGRES_PASSWORD: mysecretpassword \
      -e POSTGRES_USER: user \
      -e POSTGRES_DB: postgres_user \
      -e PGDATA: /var/lib/postgresql/data \
      -p 8080 : 8080 \
      -v C:\Users\Pepper\IdeaProjects\Docker\docker-compose.yml:/var/lib/postgresql/data \
      postgers

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080