version: '3.1'

services:
  postgres:
    image: postgres
    ports:
      - '8080:8080'
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=my_db
      - p8080:8080
      - v/data:/var/lib/postgresql
  adminer:
    image: adminer
    restart: always
